version: "{branch} {build}"

clone_depth: 5

environment:
  matrix:
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk9
    - JAVA_HOME: C:\Program Files\Java\jdk11
    - JAVA_HOME: C:\Program Files\Java\jdk12

matrix:
  fast_finish: true

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --info --no-daemon
  - gradlew.bat -p ksp assemble --info --no-daemon

test_script:
  - gradlew.bat check --info --no-daemon
  - gradlew.bat -p ksp check --info --no-daemon
