name: "Validate Gradle Wrapper"
on: [push, pull_request]

jobs:
  check_duplicate_workflows:
    name: Check for duplicate workflows
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          skip_after_successful_duplicate: 'false'
          concurrent_skipping: 'same_content'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
          paths: '["./gradle/wrapper/gradle-wrapper.jar"]'
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    needs: [check_duplicate_workflows]
    if: ${{ needs.check_duplicate_workflows.outputs.should_skip != 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v3
